# Generated by Django 5.2.17 on 2026-09-24 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='meta_description',
            field=models.CharField(blank=True, default='Inicia Legal: asesoría legal preventiva para pymes y empresas en Chile. Plan Legal Advance, contratos, laboral, tributario y penal económico.', max_length=160, verbose_name='meta descripción por defecto'),
        ),
    ]
