# Generated by Django 5.2.17 on 2026-09-24 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_shorten_meta_description_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='cookie_consent_enabled',
            field=models.BooleanField(default=True, verbose_name='mostrar aviso de cookies'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cookie_consent_text',
            field=models.TextField(blank=True, default='Este sitio web utiliza cookies y otras tecnologías, y trata los datos personales que nos proporcionas para ofrecer una mejor experiencia, atender tus solicitudes y cumplir las finalidades descritas en nuestra Política de Privacidad, de conformidad con la Ley N.° 21.719 sobre Protección de Datos Personales. Puedes aceptar, rechazar o configurar tus preferencias en cualquier momento.', verbose_name='texto del aviso'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cookie_consent_title',
            field=models.CharField(blank=True, default='Gestionar consentimiento', max_length=120, verbose_name='título del aviso'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cookie_policy_url',
            field=models.CharField(blank=True, default='/p/politica-de-cookies/', max_length=200, verbose_name='URL de la política de cookies'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='monogram',
            field=models.CharField(blank=True, default='IL', help_text='Letras gigantes que se muestran como marca de agua en el pie de página y la banda de contacto. Dejar vacío para ocultar.', max_length=4, verbose_name='monograma decorativo'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='privacy_policy_url',
            field=models.CharField(blank=True, default='/p/privacidad/', max_length=200, verbose_name='URL de la política de privacidad'),
        ),
    ]
