# Generated by Django 5.2.17 on 2026-09-24 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cookie_consent_and_monogram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_kicker',
            field=models.CharField(blank=True, default='Tu negocio, con respaldo legal', max_length=120, verbose_name='texto superior del hero'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_secondary_text',
            field=models.CharField(blank=True, default='Conoce nuestros planes', max_length=60, verbose_name='botón secundario (texto)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_subtitle',
            field=models.TextField(blank=True, default='Acompañamos a emprendedores, e-commerce, startups y pymes en cada etapa de su negocio, con asesoría estratégica, clara y orientada a resultados.', verbose_name='subtítulo del hero'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_title',
            field=models.CharField(default='Soluciones legales para empresas que *quieren crecer*', help_text='Encierra entre asteriscos la parte que quieres destacar en dorado. Ej: Soluciones legales para empresas que *quieren crecer*', max_length=200, verbose_name='título del hero'),
        ),
    ]
