# Generated by Django 5.2.17 on 2026-09-24 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_hero_copy'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_image_mobile',
            field=models.ImageField(blank=True, help_text='Opcional. Vertical o cuadrada (ej. 1200×1400 px). Si se deja vacía se usa la imagen principal.', upload_to='site/', verbose_name='imagen del hero (móvil)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Horizontal, idealmente 2560×1080 px o mayor.', upload_to='site/', verbose_name='imagen del hero'),
        ),
    ]
