# Generated by Django 5.2.17 on 2026-09-24 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_hero_image_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.CharField(blank=True, default='Los Militares N°5620, oficina N°905', max_length=200, verbose_name='dirección'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='city',
            field=models.CharField(blank=True, default='Las Condes, Santiago', max_length=100, verbose_name='ciudad'),
        ),
    ]
