# Generated by Django 5.2.17 on 2026-09-25 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_address_las_condes'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('key', models.SlugField(unique=True, verbose_name='clave')),
                ('variant', models.CharField(choices=[('overlay', 'Texto sobre la imagen'), ('art', 'La imagen ya trae el mensaje'), ('plan', 'Panel del plan')], default='overlay', max_length=20, verbose_name='estilo')),
                ('kicker', models.CharField(blank=True, max_length=120, verbose_name='texto superior')),
                ('title', models.CharField(blank=True, help_text='Encierra entre asteriscos la parte que quieres destacar en dorado.', max_length=200, verbose_name='título')),
                ('subtitle', models.TextField(blank=True, verbose_name='subtítulo')),
                ('image', models.ImageField(blank=True, help_text='Horizontal, idealmente 2560×1080 px o mayor.', upload_to='site/hero/', verbose_name='imagen')),
                ('primary_text', models.CharField(blank=True, max_length=60, verbose_name='botón principal')),
                ('primary_url', models.CharField(blank=True, max_length=200, verbose_name='URL principal')),
                ('secondary_text', models.CharField(blank=True, max_length=60, verbose_name='botón secundario')),
                ('secondary_url', models.CharField(blank=True, max_length=200, verbose_name='URL secundaria')),
            ],
            options={
                'verbose_name': 'diapositiva del inicio',
                'verbose_name_plural': 'carrusel del inicio',
                'ordering': ['order', 'id'],
            },
        ),
    ]
