# Generated by Django 5.2.17 on 2026-09-25 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_hero_slides'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_kicker',
            field=models.CharField(blank=True, default='Tu empresa, con respaldo legal', max_length=120, verbose_name='texto superior del hero'),
        ),
    ]
