# Generated by Django 5.2.17 on 2026-09-29 05:13

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_newsletter_privacy_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='answer_en',
            field=models.TextField(null=True, verbose_name='respuesta'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_es_cl',
            field=models.TextField(null=True, verbose_name='respuesta'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_en',
            field=models.CharField(max_length=255, null=True, verbose_name='pregunta'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_es_cl',
            field=models.CharField(max_length=255, null=True, verbose_name='pregunta'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='kicker_en',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='texto superior'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='kicker_es_cl',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='texto superior'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='primary_text_en',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='botón principal'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='primary_text_es_cl',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='botón principal'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='secondary_text_en',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='botón secundario'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='secondary_text_es_cl',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='botón secundario'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='subtitle_en',
            field=models.TextField(blank=True, null=True, verbose_name='subtítulo'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='subtitle_es_cl',
            field=models.TextField(blank=True, null=True, verbose_name='subtítulo'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='title_en',
            field=models.CharField(blank=True, help_text='Encierra entre asteriscos la parte que quieres destacar en dorado.', max_length=200, null=True, verbose_name='título'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='title_es_cl',
            field=models.CharField(blank=True, help_text='Encierra entre asteriscos la parte que quieres destacar en dorado.', max_length=200, null=True, verbose_name='título'),
        ),
        migrations.AddField(
            model_name='page',
            name='content_en',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='contenido'),
        ),
        migrations.AddField(
            model_name='page',
            name='content_es_cl',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='contenido'),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_description_en',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='meta descripción'),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_description_es_cl',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='meta descripción'),
        ),
        migrations.AddField(
            model_name='page',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='subtítulo'),
        ),
        migrations.AddField(
            model_name='page',
            name='subtitle_es_cl',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='subtítulo'),
        ),
        migrations.AddField(
            model_name='page',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='título'),
        ),
        migrations.AddField(
            model_name='page',
            name='title_es_cl',
            field=models.CharField(max_length=200, null=True, verbose_name='título'),
        ),
        migrations.AddField(
            model_name='plan',
            name='cta_text_en',
            field=models.CharField(default='Quiero este plan', max_length=60, null=True, verbose_name='texto del botón'),
        ),
        migrations.AddField(
            model_name='plan',
            name='cta_text_es_cl',
            field=models.CharField(default='Quiero este plan', max_length=60, null=True, verbose_name='texto del botón'),
        ),
        migrations.AddField(
            model_name='plan',
            name='discount_badge_en',
            field=models.CharField(blank=True, default='Hasta 40% de descuento en servicios adicionales', max_length=120, null=True, verbose_name='beneficio destacado'),
        ),
        migrations.AddField(
            model_name='plan',
            name='discount_badge_es_cl',
            field=models.CharField(blank=True, default='Hasta 40% de descuento en servicios adicionales', max_length=120, null=True, verbose_name='beneficio destacado'),
        ),
        migrations.AddField(
            model_name='plan',
            name='discount_text_en',
            field=models.TextField(blank=True, null=True, verbose_name='beneficio · texto'),
        ),
        migrations.AddField(
            model_name='plan',
            name='discount_text_es_cl',
            field=models.TextField(blank=True, null=True, verbose_name='beneficio · texto'),
        ),
        migrations.AddField(
            model_name='plan',
            name='name_en',
            field=models.CharField(max_length=120, null=True, verbose_name='nombre'),
        ),
        migrations.AddField(
            model_name='plan',
            name='name_es_cl',
            field=models.CharField(max_length=120, null=True, verbose_name='nombre'),
        ),
        migrations.AddField(
            model_name='plan',
            name='price_note_en',
            field=models.CharField(blank=True, default='Medios de pago: transferencia electrónica, tarjeta de débito o crédito.', max_length=200, null=True, verbose_name='nota de precio'),
        ),
        migrations.AddField(
            model_name='plan',
            name='price_note_es_cl',
            field=models.CharField(blank=True, default='Medios de pago: transferencia electrónica, tarjeta de débito o crédito.', max_length=200, null=True, verbose_name='nota de precio'),
        ),
        migrations.AddField(
            model_name='plan',
            name='problem_text_en',
            field=models.TextField(blank=True, null=True, verbose_name='sección problema · texto'),
        ),
        migrations.AddField(
            model_name='plan',
            name='problem_text_es_cl',
            field=models.TextField(blank=True, null=True, verbose_name='sección problema · texto'),
        ),
        migrations.AddField(
            model_name='plan',
            name='problem_title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='sección problema · título'),
        ),
        migrations.AddField(
            model_name='plan',
            name='problem_title_es_cl',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='sección problema · título'),
        ),
        migrations.AddField(
            model_name='plan',
            name='solution_text_en',
            field=models.TextField(blank=True, null=True, verbose_name='sección solución · texto'),
        ),
        migrations.AddField(
            model_name='plan',
            name='solution_text_es_cl',
            field=models.TextField(blank=True, null=True, verbose_name='sección solución · texto'),
        ),
        migrations.AddField(
            model_name='plan',
            name='solution_title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='sección solución · título'),
        ),
        migrations.AddField(
            model_name='plan',
            name='solution_title_es_cl',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='sección solución · título'),
        ),
        migrations.AddField(
            model_name='plan',
            name='summary_en',
            field=models.TextField(blank=True, null=True, verbose_name='resumen'),
        ),
        migrations.AddField(
            model_name='plan',
            name='summary_es_cl',
            field=models.TextField(blank=True, null=True, verbose_name='resumen'),
        ),
        migrations.AddField(
            model_name='plan',
            name='tagline_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='bajada'),
        ),
        migrations.AddField(
            model_name='plan',
            name='tagline_es_cl',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='bajada'),
        ),
        migrations.AddField(
            model_name='planbenefit',
            name='text_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='detalle'),
        ),
        migrations.AddField(
            model_name='planbenefit',
            name='text_es_cl',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='detalle'),
        ),
        migrations.AddField(
            model_name='planbenefit',
            name='title_en',
            field=models.CharField(max_length=120, null=True, verbose_name='título'),
        ),
        migrations.AddField(
            model_name='planbenefit',
            name='title_es_cl',
            field=models.CharField(max_length=120, null=True, verbose_name='título'),
        ),
        migrations.AddField(
            model_name='planfeature',
            name='text_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='detalle'),
        ),
        migrations.AddField(
            model_name='planfeature',
            name='text_es_cl',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='detalle'),
        ),
        migrations.AddField(
            model_name='planfeature',
            name='title_en',
            field=models.CharField(max_length=120, null=True, verbose_name='título'),
        ),
        migrations.AddField(
            model_name='planfeature',
            name='title_es_cl',
            field=models.CharField(max_length=120, null=True, verbose_name='título'),
        ),
        migrations.AddField(
            model_name='practicearea',
            name='description_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='descripción completa'),
        ),
        migrations.AddField(
            model_name='practicearea',
            name='description_es_cl',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='descripción completa'),
        ),
        migrations.AddField(
            model_name='practicearea',
            name='name_en',
            field=models.CharField(max_length=120, null=True, verbose_name='nombre'),
        ),
        migrations.AddField(
            model_name='practicearea',
            name='name_es_cl',
            field=models.CharField(max_length=120, null=True, verbose_name='nombre'),
        ),
        migrations.AddField(
            model_name='practicearea',
            name='short_description_en',
            field=models.CharField(max_length=255, null=True, verbose_name='descripción corta'),
        ),
        migrations.AddField(
            model_name='practicearea',
            name='short_description_es_cl',
            field=models.CharField(max_length=255, null=True, verbose_name='descripción corta'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='descripción completa'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_es_cl',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='descripción completa'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_en',
            field=models.CharField(max_length=120, null=True, verbose_name='nombre'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_es_cl',
            field=models.CharField(max_length=120, null=True, verbose_name='nombre'),
        ),
        migrations.AddField(
            model_name='service',
            name='price_note_en',
            field=models.CharField(blank=True, help_text="Ej: Desde $150.000 + IVA, o 'Cotizar'.", max_length=120, null=True, verbose_name='nota de precio'),
        ),
        migrations.AddField(
            model_name='service',
            name='price_note_es_cl',
            field=models.CharField(blank=True, help_text="Ej: Desde $150.000 + IVA, o 'Cotizar'.", max_length=120, null=True, verbose_name='nota de precio'),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description_en',
            field=models.CharField(max_length=255, null=True, verbose_name='descripción corta'),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description_es_cl',
            field=models.CharField(max_length=255, null=True, verbose_name='descripción corta'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_kicker_en',
            field=models.CharField(blank=True, default='Quiénes somos', max_length=120, null=True, verbose_name='nosotros · texto superior'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_kicker_es_cl',
            field=models.CharField(blank=True, default='Quiénes somos', max_length=120, null=True, verbose_name='nosotros · texto superior'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_text_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='nosotros · texto'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_text_es_cl',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='nosotros · texto'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_title_en',
            field=models.CharField(blank=True, default='Un equipo jurídico que previene antes de corregir', max_length=200, null=True, verbose_name='nosotros · título'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_title_es_cl',
            field=models.CharField(blank=True, default='Un equipo jurídico que previene antes de corregir', max_length=200, null=True, verbose_name='nosotros · título'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cookie_consent_text_en',
            field=models.TextField(blank=True, default='Este sitio web utiliza cookies y otras tecnologías, y trata los datos personales que nos proporcionas para ofrecer una mejor experiencia, atender tus solicitudes y cumplir las finalidades descritas en nuestra Política de Privacidad, de conformidad con la Ley N.° 21.719 sobre Protección de Datos Personales. Puedes aceptar, rechazar o configurar tus preferencias en cualquier momento.', null=True, verbose_name='texto del aviso'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cookie_consent_text_es_cl',
            field=models.TextField(blank=True, default='Este sitio web utiliza cookies y otras tecnologías, y trata los datos personales que nos proporcionas para ofrecer una mejor experiencia, atender tus solicitudes y cumplir las finalidades descritas en nuestra Política de Privacidad, de conformidad con la Ley N.° 21.719 sobre Protección de Datos Personales. Puedes aceptar, rechazar o configurar tus preferencias en cualquier momento.', null=True, verbose_name='texto del aviso'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cookie_consent_title_en',
            field=models.CharField(blank=True, default='Gestionar consentimiento', max_length=120, null=True, verbose_name='título del aviso'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cookie_consent_title_es_cl',
            field=models.CharField(blank=True, default='Gestionar consentimiento', max_length=120, null=True, verbose_name='título del aviso'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_button_text_en',
            field=models.CharField(blank=True, default='Contáctanos', max_length=60, null=True, verbose_name='CTA · botón'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_button_text_es_cl',
            field=models.CharField(blank=True, default='Contáctanos', max_length=60, null=True, verbose_name='CTA · botón'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_text_en',
            field=models.TextField(blank=True, default='Conversemos. Agenda una reunión inicial sin costo y descubre cómo podemos acompañarte durante todo el año.', null=True, verbose_name='CTA · texto'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_text_es_cl',
            field=models.TextField(blank=True, default='Conversemos. Agenda una reunión inicial sin costo y descubre cómo podemos acompañarte durante todo el año.', null=True, verbose_name='CTA · texto'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_title_en',
            field=models.CharField(blank=True, default='¿Tu empresa está tomando decisiones legales a tiempo?', max_length=200, null=True, verbose_name='CTA · título'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_title_es_cl',
            field=models.CharField(blank=True, default='¿Tu empresa está tomando decisiones legales a tiempo?', max_length=200, null=True, verbose_name='CTA · título'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_text_en',
            field=models.TextField(blank=True, default='Estudio jurídico especializado en asesoría legal preventiva para empresas. Acompañamos tus decisiones con un equipo experto en materias civil, comercial, laboral, tributaria y penal económica.', null=True, verbose_name='texto del pie de página'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_text_es_cl',
            field=models.TextField(blank=True, default='Estudio jurídico especializado en asesoría legal preventiva para empresas. Acompañamos tus decisiones con un equipo experto en materias civil, comercial, laboral, tributaria y penal económica.', null=True, verbose_name='texto del pie de página'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_description_en',
            field=models.CharField(blank=True, default='Inicia Legal: asesoría legal preventiva para pymes y empresas en Chile. Plan Legal Advance, contratos, laboral, tributario y penal económico.', max_length=160, null=True, verbose_name='meta descripción por defecto'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_description_es_cl',
            field=models.CharField(blank=True, default='Inicia Legal: asesoría legal preventiva para pymes y empresas en Chile. Plan Legal Advance, contratos, laboral, tributario y penal económico.', max_length=160, null=True, verbose_name='meta descripción por defecto'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='schedule_en',
            field=models.CharField(blank=True, default='Lunes a viernes, 9:00 a 18:00 hrs.', max_length=120, null=True, verbose_name='horario de atención'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='schedule_es_cl',
            field=models.CharField(blank=True, default='Lunes a viernes, 9:00 a 18:00 hrs.', max_length=120, null=True, verbose_name='horario de atención'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tagline_en',
            field=models.CharField(blank=True, default='Respaldo legal permanente para empresas que quieren operar con seguridad.', max_length=200, null=True, verbose_name='eslogan'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tagline_es_cl',
            field=models.CharField(blank=True, default='Respaldo legal permanente para empresas que quieren operar con seguridad.', max_length=200, null=True, verbose_name='eslogan'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_message_en',
            field=models.CharField(default='Hola, me gustaría recibir más información sobre los servicios de Inicia Legal.', max_length=200, null=True, verbose_name='mensaje inicial WhatsApp'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_message_es_cl',
            field=models.CharField(default='Hola, me gustaría recibir más información sobre los servicios de Inicia Legal.', max_length=200, null=True, verbose_name='mensaje inicial WhatsApp'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='bio_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='biografía'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='bio_es_cl',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='biografía'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='role_en',
            field=models.CharField(default='Abogado/a', max_length=120, null=True, verbose_name='cargo'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='role_es_cl',
            field=models.CharField(default='Abogado/a', max_length=120, null=True, verbose_name='cargo'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='specialty_en',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='especialidad'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='specialty_es_cl',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='especialidad'),
        ),
    ]
