# Generated by Django 5.2.17 on 2026-09-24 20:34

import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nombre')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('color', models.CharField(default='#B5924C', help_text='Color hexadecimal, ej: #B5924C', max_length=7, verbose_name='color')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='nombre')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'etiqueta',
                'verbose_name_plural': 'etiquetas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('author_display', models.CharField(blank=True, help_text="Si se deja vacío se usa el nombre del usuario o 'Equipo Inicia Legal'.", max_length=120, verbose_name='nombre de autor a mostrar')),
                ('excerpt', models.TextField(blank=True, help_text='Resumen breve para listados y redes. Si se deja vacío se genera automáticamente.', max_length=400, verbose_name='extracto')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='contenido')),
                ('cover_image', models.ImageField(blank=True, upload_to='blog/%Y/%m/', verbose_name='imagen de portada')),
                ('cover_caption', models.CharField(blank=True, max_length=200, verbose_name='leyenda de la imagen')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado')], default='draft', max_length=10, verbose_name='estado')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Puede programarse a futuro.', verbose_name='fecha de publicación')),
                ('is_featured', models.BooleanField(default=False, verbose_name='destacado')),
                ('allow_comments', models.BooleanField(default=True, verbose_name='permitir comentarios')),
                ('views', models.PositiveIntegerField(default=0, editable=False, verbose_name='visitas')),
                ('meta_title', models.CharField(blank=True, max_length=70, verbose_name='meta título')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='meta descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('areas', models.ManyToManyField(blank=True, related_name='posts', to='core.practicearea', verbose_name='áreas relacionadas')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.category', verbose_name='categoría')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='blog.tag', verbose_name='etiquetas')),
            ],
            options={
                'verbose_name': 'artículo',
                'verbose_name_plural': 'artículos',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('body', models.TextField(max_length=2000, verbose_name='comentario')),
                ('is_approved', models.BooleanField(default=False, verbose_name='aprobado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post')),
            ],
            options={
                'verbose_name': 'comentario',
                'verbose_name_plural': 'comentarios',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['status', 'published_at'], name='blog_post_status_5b2843_idx'),
        ),
    ]
