# Generated by Django 5.2.17 on 2026-09-29 05:13

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_es_cl',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='nombre'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_es_cl',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='nombre'),
        ),
        migrations.AddField(
            model_name='post',
            name='content_en',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='contenido'),
        ),
        migrations.AddField(
            model_name='post',
            name='content_es_cl',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='contenido'),
        ),
        migrations.AddField(
            model_name='post',
            name='cover_caption_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='leyenda de la imagen'),
        ),
        migrations.AddField(
            model_name='post',
            name='cover_caption_es_cl',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='leyenda de la imagen'),
        ),
        migrations.AddField(
            model_name='post',
            name='excerpt_en',
            field=models.TextField(blank=True, help_text='Resumen breve para listados y redes. Si se deja vacío se genera automáticamente.', max_length=400, null=True, verbose_name='extracto'),
        ),
        migrations.AddField(
            model_name='post',
            name='excerpt_es_cl',
            field=models.TextField(blank=True, help_text='Resumen breve para listados y redes. Si se deja vacío se genera automáticamente.', max_length=400, null=True, verbose_name='extracto'),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_description_en',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='meta descripción'),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_description_es_cl',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='meta descripción'),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='meta título'),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_title_es_cl',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='meta título'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='título'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_es_cl',
            field=models.CharField(max_length=200, null=True, verbose_name='título'),
        ),
    ]
