# Generated by Django 5.2 for inicialegal.cl

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AssistantConversation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("session_key", models.CharField(blank=True, db_index=True, max_length=80, verbose_name="sesion")),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True, verbose_name="IP")),
                ("user_agent", models.CharField(blank=True, max_length=255, verbose_name="user agent")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="creada")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="actualizada")),
            ],
            options={
                "verbose_name": "conversacion del asistente",
                "verbose_name_plural": "conversaciones del asistente",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="AssistantKnowledgeItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_type", models.CharField(choices=[("faq", "Pregunta frecuente"), ("service", "Servicio"), ("area", "Area de practica"), ("plan", "Plan"), ("page", "Pagina"), ("post", "Articulo")], max_length=20, verbose_name="tipo")),
                ("source_id", models.PositiveBigIntegerField(verbose_name="ID de origen")),
                ("title", models.CharField(max_length=240, verbose_name="titulo")),
                ("summary", models.TextField(blank=True, verbose_name="resumen")),
                ("content", models.TextField(verbose_name="contenido")),
                ("url", models.CharField(blank=True, max_length=255, verbose_name="URL")),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                ("source_updated_at", models.DateTimeField(blank=True, null=True, verbose_name="actualizado en origen")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="creado")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="actualizado")),
            ],
            options={
                "verbose_name": "contenido del asistente",
                "verbose_name_plural": "contenidos del asistente",
                "ordering": ["source_type", "title"],
            },
        ),
        migrations.CreateModel(
            name="AssistantMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("role", models.CharField(choices=[("user", "Usuario"), ("assistant", "Asistente")], max_length=12, verbose_name="rol")),
                ("content", models.TextField(verbose_name="contenido")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="creado")),
                ("conversation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="assistant.assistantconversation")),
            ],
            options={
                "verbose_name": "mensaje del asistente",
                "verbose_name_plural": "mensajes del asistente",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="assistantknowledgeitem",
            index=models.Index(fields=["source_type", "is_active"], name="assistant_a_source__f04339_idx"),
        ),
        migrations.AddIndex(
            model_name="assistantknowledgeitem",
            index=models.Index(fields=["is_active", "updated_at"], name="assistant_a_is_acti_61e180_idx"),
        ),
        migrations.AddConstraint(
            model_name="assistantknowledgeitem",
            constraint=models.UniqueConstraint(fields=("source_type", "source_id"), name="assistant_unique_source"),
        ),
    ]
